name: Build and Release Dev Browser Extension

on:
  push:
    branches:
      - main

jobs:
  build_and_release_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.RELEASE_PAT }}

    # Build Chrome Extension
    - name: Build Chrome Extension
      run: |
        zip -r chrome-extension-dev.zip . -x "*.git*" "docs*"

    # Generate and push a release tag
    - name: Generate and Push Dev Tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        # Using a unique tag for dev releases
        git tag -fa dev-latest -m "Latest development auto-release"
        git push https://${{ secrets.RELEASE_PAT }}@github.com/${{ github.repository }}.git --tags --force
      shell: bash

    # Create GitHub Release and upload artifacts (using 'dev-latest' tag)
    - name: Create and Upload Dev Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-latest
        token: ${{ secrets.RELEASE_PAT }}
        draft: false
        files: |
          ./chrome-extension-dev.zip
