name: Versioned Build and Release Browser Extension

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.RELEASE_PAT }}

    - name: Check if version has changed
      run: |
        VERSION=$(jq -r '.version' manifest.json)
        echo "Version in manifest: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Get the latest tag version
      run: |
        LATEST_TAG=$(git tag | grep $VERSION || echo "not found")
        echo "Latest tag: $LATEST_TAG"
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV
      shell: bash

    - name: Compare versions or check for tag existence
      run: |
        if [ "$latest_tag" == "not found" ]; then
          echo "version_changed=true" >> $GITHUB_ENV
        else
          echo "version_changed=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build Chrome Extension
      if: env.version_changed == 'true'
      run: |
        zip -r chrome-extension-$version.zip . -x "*.git*" "docs*"

    - name: Generate and Push Tag
      if: env.version_changed == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -fa $version -m "Release $version"
        git push https://${{ secrets.RELEASE_PAT }}@github.com/${{ github.repository }}.git --tags --force
      shell: bash

    - name: Create and Upload Release
      if: env.version_changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $version
        token: ${{ secrets.RELEASE_PAT }}
        draft: false
        files: |
          ./chrome-extension-$version.zip
